# Generated by Django 4.1.5 on 2023-01-27 22:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_and_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(default=True, help_text='add name for your event!', max_length=30, unique=True, verbose_name='Event name'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_pic',
            field=models.ImageField(default=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(default=True, max_length=30),
        ),
    ]
