# Generated by Django 4.1.5 on 2023-01-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="date_and_time",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="event_pic",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="event_name",
            new_name="name",
        ),
    ]
