# Generated by Django 4.1.5 on 2023-01-30 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_rename_organizer_event_organiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='', help_text='add name for your event!', max_length=30, unique=True, verbose_name='Event name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organiser',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
